name: Deploy to GitHub Pages

on:
  push:
    branches:
      - master # Trigger the action on push to master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Copy frontend files to root
        run: |
          cp -r weather/* .

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: . # Root directory where files are copied
